name: Build iOS

on:
  # Вимкнено тимчасово через помилки
  # push:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS без підпису
      run: |
        flutter build ios --release --no-codesign
    
    - name: Create simple IPA
      run: |
        mkdir -p build/ios/ipa
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -R Runner.app Payload/
        cd ../../../
        zip -r build/ios/ipa/tetris-flutter.ipa build/ios/iphoneos/Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: tetris-flutter-ios
        path: build/ios/ipa/tetris-flutter.ipa